name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: actions/cache@v3.0.8
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Download OpenCV SDK
        run: sh ./.github/download_opencv_sdk.sh
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.7
      - run: sdkmanager platform-tools
      - run: adb devices
      - run: echo $ANDROID_HOME
      - name: Instrumented Test
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.7
        with:
          cmd: ./gradlew connectedAndroidTest
          api: 28
          tag: default
          abi: armeabi-v7a
